version: "3.9"
services:
  minerid:
    build: .
    ports:
      - 9002:9002
    restart: always
    environment:
      NODE_CONFIG: '{
        "bitcoin": {
        "rpcHost":"host.docker.internal"
        },
        "network": "livenet"
        }'
    volumes:
      - minerid:/root/.keystore
      - minerid:/root/.revocationkeystore
      - minerid:/root/.minerid-client
volumes:
  minerid:
    external: false
